### ISSUE TITLE
Error building a branch / ref distinct that the repository **default** branch

### ISSUE THREAD

**Issue by alambike** [prefapp/firestarter-workflows#137]
### Description
The following error happens when you try to build other branch different that de repository default branch

```
    INPUT_SECRETS: 
    INPUT_CONFIG_FILE: ../config/.github/build_images.yaml
[INFO][/home/runner/.cache/pypoetry/virtualenvs/firestarter-workflows-7CHOyqa4-py3.11/bin/firestarter] Running workflow build_images with vars {'repo_name': 'xxx/xxx-client', 'flavors': 'dev', 'auth_strategy': 'azure_oidc', 'snapshots_registry': 'xxx.azurecr.io', 'releases_registry': 'yyy.azurecr.io', 'output_results': 'build_images_results.yaml', 'type': 'snapshots', 'from': 'dev', 'workflow_run_id': 1133322222, 'workflow_run_url': 'https://github.com/xxx/xxx-client/actions/runs/1133322222', 'login_required': 'true', 'service_path': 'service', 'snapshots_registry_creds': '', 'releases_registry_creds': ''} and secrets {}
fatal: ambiguous argument 'dev': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/xxx-client/xxx-client/workflows/firestarter/cli/parser.py", line 46, in main
    result = workflow.run(
             ^^^^^^^^^^^^^
  File "/home/runner/work/xxx-client/xxx-client/workflows/firestarter/workflows/build_images/__init__.py", line 4, in run
    wf = BuildImages(vars=vars, secrets=secrets, config_file=config_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/xxx-client/xxx-client/workflows/firestarter/workflows/build_images/build_images.py", line 41, in __init__
    self._from = self.dereference_from_input(self.vars.get('from'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/xxx-client/xxx-client/workflows/firestarter/workflows/build_images/build_images.py", line 213, in dereference_from_input
    proc.check_returncode()
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'dev']' returned non-zero exit status 128.
```

**Comment by alambike** [comment]
The problem is related to https://github.com/prefapp/firestarter-workflows/pull/121

The issue arises in the new checkout step:

https://github.com/prefapp/firestarter-workflows/blob/0eddbb66a1d4b61f9d23ddc84d2189b1c993cf2c/.github/workflows/build_images.yaml#L93-L97

- no tags are checked out, you would need to **expressly** pull them using the `fetch-tags` checkout flag
- If no heads are created locally except the checkout branch, the `git rev-parse` sub-process will fail if the action is not configured to checkout the `inputs.from`
